name: Deploy Astro from CodeTransEngine to codetransengine.github.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (CodeTransEngine)
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build Astro site
        working-directory: docs
        run: npm run build

      - name: Add .nojekyll
        run: touch docs/dist/.nojekyll

      - name: Deploy to codetransengine.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: CodeTransEngine/codetransengine.github.io
          publish_branch: main
          publish_dir: docs/dist
          destination_dir: .
          force_orphan: true